### PR TITLE
fix: consumer never stops when max poll is exceeded

### LINKED ISSUE #492: [Bug Report]: Consumer Stuck on Exceeding Max Poll Interval
### Prerequisites

- [X] I have searched [issues](https://github.com/Farfetch/kafkaflow/issues) to ensure it has not already been reported

### Description

The consumer may become unresponsive if it exceeds the maximum polling interval and is then requested to stop.

### Steps to reproduce

1. Create a new consumer.

2. Make sure to configure the consumer with a short maximum poll interval.

3. Create a scenario where the consumer takes more time than the configured maximum poll interval by adding an artificial delay.

4. Once the maximum poll interval has been exceeded, the partitions will be revoked and the consumer will be asked to stop. After that, the StopAsync() method will remain blocked indefinitely.

### Expected behavior

The consumer must stop immediately when the partition is revoked due to exceeding the maximum poll interval.

### Actual behavior

The consumer gets stuck and never stops.

### KafkaFlow version

v3.0.1

### PR DESCRIPTION
**Pull request by filipeesch**
# Description

Implemented synchronization mechanisms for immediate consumer shutdown upon partition revocation, triggered by exceeding the 'max poll interval'. Additionally, integrated the 'stop worker timeout' configuration to effectively cancel ongoing message processing when a stop request is issued, ensuring a smooth and non-blocking stop procedure.

Fixes #492 

## How Has This Been Tested?

Manual and automated tests

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [ ] I have added tests to cover my changes
-   [ ] I have made corresponding changes to the documentation

### Disclaimer

By sending us your contributions, you are agreeing that your contribution is made subject to the terms of our [Contributor Ownership Statement](https://github.com/Farfetch/.github/blob/master/COS.md)

### CODE REVIEW

File: src/KafkaFlow/Consumers/IConsumer.cs [hunk 1]
```diff
@@ -48,13 +53,15 @@ public interface IConsumer : IDisposable
...
+    void OnPartitionsAssigned(
+        Action<IDependencyResolver, Confluent.Kafka.IConsumer<byte[], byte[]>, List<Confluent.Kafka.TopicPartition>> handler);
 
     /// <summary>
     /// Register a handler to be executed when the partitions are revoked
     /// </summary>
     /// <param name="handler">The handler that will be executed</param>
-    void OnPartitionsRevoked(Action<IDependencyResolver, Confluent.Kafka.IConsumer<byte[], byte[]>, List<Confluent.Kafka.TopicPartitionOffset>> handler);
+    void OnPartitionsRevoked(
+        Action<IDependencyResolver, Confluent.Kafka.IConsumer<byte[], byte[]>, List<Confluent.Kafka.TopicPartitionOffset>> handler);
```
Comment (joelfoliveira) [inline src/KafkaFlow/Consumers/IConsumer.cs:64]: same as https://github.com/Farfetch/kafkaflow/pull/493/files?diff=split&w=1#r1424341498

File: src/KafkaFlow/Extensions/MessageContextExtensions.cs [hunk 2]
```diff
@@ -0,0 +1,10 @@
+namespace KafkaFlow.Extensions;
+
+internal static class MessageContextExtensions
+{
+    public static void Discard(this IConsumerContext context)
```
Comment (joelfoliveira) [inline src/KafkaFlow/Extensions/MessageContextExtensions.cs:5]: Why an extension method? and not on the ConsumerContext itself?

**Review by joelfoliveira — APPROVED** [review]

**Review by ruiqbarbosa — APPROVED** [review]

File: src/KafkaFlow/Extensions/MessageContextExtensions.cs (hunk 2 above)
Comment (filipeesch) [reply src/KafkaFlow/Extensions/MessageContextExtensions.cs:5]: I believe this method meets the requirements of an extension method, as it solely utilizes the public members of the `IConsumerContext`. Therefore, any implementation of this interface will have the capability to use the method.

File: src/KafkaFlow/Consumers/IConsumer.cs (hunk 1 above)
Comment (filipeesch) [reply src/KafkaFlow/Consumers/IConsumer.cs]: done

File: src/KafkaFlow/Consumers/IConsumer.cs [hunk 3]
```diff
@@ -48,13 +53,15 @@ public interface IConsumer : IDisposable
     /// Register a handler to be executed when the partitions are assigned
     /// </summary>
     /// <param name="handler">The handler that will be executed</param>
-    void OnPartitionsAssigned(Action<IDependencyResolver, Confluent.Kafka.IConsumer<byte[], byte[]>, List<Confluent.Kafka.TopicPartition>> handler);
+    void OnPartitionsAssigned(
+        Action<IDependencyResolver, Confluent.Kafka.IConsumer<byte[], byte[]>, List<Confluent.Kafka.TopicPartition>> handler);
```
[the remark this answers is not in the document]
Comment (filipeesch) [reply src/KafkaFlow/Consumers/IConsumer.cs]: done

**Review by brmagadutra — APPROVED** [review]

File: src/KafkaFlow/Consumers/Consumer.cs [hunk 4]
```diff
@@ -34,9 +37,8 @@ internal class Consumer : IConsumer
         _dependencyResolver = dependencyResolver;
         _logHandler = logHandler;
         this.Configuration = configuration;
-        _flowManager = new ConsumerFlowManager(
-            this,
-            _logHandler);
+        _flowManager = new ConsumerFlowManager(this, _logHandler);
+        _maxPollIntervalExceeded = new(_logHandler);
```
Comment (brmagadutra) [inline src/KafkaFlow/Consumers/Consumer.cs:41]: Is it possible to add tests to these scenarios?

Comment (filipeesch) [reply src/KafkaFlow/Consumers/Consumer.cs:41]: Without a well-defined integrated test strategy, I would say that the answer is no.

**Review by lpsc82 — APPROVED** [review]

**Review by JoaoRodriguesGithub — APPROVED** [review]
